;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        c-electric-semi&comma
        cljr-raise-sexp
        forward-sexp
        gh/smarter-move-beginning-of-line
        kill-region
        kill-sexp
        paredit-backward
        paredit-backward-down
        paredit-backward-kill-word
        paredit-backward-up
        paredit-forward
        paredit-forward-barf-sexp
        paredit-forward-delete
        paredit-forward-down
        paredit-forward-slurp-sexp
        paredit-forward-up
        paredit-meta-doublequote
        paredit-newline
        paredit-open-curly
        paredit-open-round
        paredit-wrap-round
        paredit-wrap-square
        racket--paredit-open-square
        ))

(setq mc/cmds-to-run-once
      '(
        abbrev-prefix-mark
        cider-find-and-clear-repl-output
        cljr-slash
        smex
        ))
